### ISSUE TITLE
Lots of false error pop up after a file is reformatted

### ISSUE THREAD

**Issue by WhyNotHugo** [pappasam/jedi-language-server#128] opened 2021-04-09 20:55 UTC
After I reformat a file with `black` (using `ale`), the LSP starts to misbehave and shows lots of bogus parsing errors.

https://user-images.githubusercontent.com/730811/114239596-cc22fb00-9975-11eb-914f-08fbe85f4ab3.mp4

I can't help notice that it cascades from top to bottom. The top pane is the same file 100 lines up.

**Comment by pappasam** [comment] 2021-04-09 21:02
Wow, that's quite the strobe light of silly linting messages! To help us debug, would you please let me know:

1. Your editor (Vim, Neovim, version, etc?)
2. Your LSP client (coc, built-in, Ale, etc)?
3. How you configure jedi-language-server to work with your client (manually, client configures it for you, other)?
4. The version of jedi-language-server that you're using?
5. Your Python version>
6. Anything else you can think of that might be of use?

**Comment by WhyNotHugo** [comment] 2021-04-09 21:19
Oh, I won't say I dislike it, it has a very x-mas-like feel to it.

1. Neovim nightly (0.4.0.r3064.gfa4ee00fa-1)
2. Neovim's built-in LSP client.
2. LSP is configured via [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig).
4. `jedi-language-server` 0.30.2 (from the Arch repositories). It doesn't have any patches, it's the clean upstream tarball.
5. Python 3.9.2
6. Some more details exploring this:

- If I copy and paste a 1500 line file, it doesn't happen.
- If I unformat two lines, and then run `black` on the via (via `ale`), it does.
- If I unformat two lines, and run `black` on a terminal, it also does this (note that `nvim` auto-reloads).
- It doesn't actually seem to always be top-to-bottom file wise. It's just top-to-bottom in each split.

By unformatting I mean turning this:

```python
def func(hello):
     return 1
```

Into this (just one change is enough):

```python
def func(hello
):
               return         (
1)
```

If I run black and it applies no changes, then it doesn't seem to happen.

**Comment by pappasam** [comment] 2021-04-09 21:29
Are there any user actions that can cause this behavior to stop? For example, when you save the file with `:write` after reformatting, do the error messages go away?

This could be caused by a variety of issues, but I'm guessing there's a bug with Neovim's built-in LSP. I say this because the strobe light effect implies that the client is sending a lot of requests to the language server due to some file modification events being fired by a code formatter outside of the language server itself.

Do you notice this effect on any other language servers when you use ALE to format code? I personally use neither of the tools you've mentioned (I'm a coc user and do code formatting with my own plugin: https://github.com/pappasam/vim-filetype-formatter).

In the short-term, if the formatting is annoying to you and you're just looking for a work-around, you might consider disabling Jedi's diagnostics. See: <https://github.com/pappasam/jedi-language-server#configuration>

**Comment by pappasam** [comment] 2021-04-09 21:31
That said, as I said, the false diagnostics may indicate a deeper problem, do I do appreciate your help debugging this.

If you're game, I could also use some logs. See the logging configuration above, I've provided a way to pass it to a file using the CLI here: https://github.com/pappasam/jedi-language-server#command-line

Not sure how you'd configure with with nvim-lsp specifically, but I'm sure there's a way

**Comment by WhyNotHugo** [comment] 2021-04-09 21:56
Saving the file doesn't seem to stop it. `:e` does not stop it either.

I've also though of neovim sending too many events when black modifies the file. Maybe the error is on the neovim/ale side.

If the LSP has a large queue of events though, shouldn't it prioritise reading from that queue, and _then_ find parsing errors? I'm guessing that this would happen if parsing happens concurrently to processing these events, right?

I rely on the diagnostics a lot, so I'll leave them on. It's not a huge deal; it's not terribly frequent due to usage.

Lemme figure out how to pass extra flags to the server using nvim-lspconfig and see what the logs say.

**Comment by WhyNotHugo** [comment] 2021-04-12 09:47
I set up logging (`--verbose --log-file .../jedi.log`). I then opened a file, change two lines, and reformatted using black. I log is **huge**. Apparently, nvim is notifying of a line change for every single line (even though just 3-4 changed).

https://share.whynothugo.nl/8343cf89-400d-4120-95f6-4fec33509d9d/jedi.log

**Comment by pappasam** [comment] 2021-04-12 22:12
Got it, so this may be a Neovim issue. When a file is changed externally, the built-in LSP client appears to be sending unnecessary didChange messages.

Are you able to replicate this behavior with any other language servers? For example, if you format a typescript file with [prettier](https://github.com/prettier/prettier) using Ale, do you observe similar behavior when getting diagnostics from Neovim's built-in language client? Replace typescript with any other language that you're able to configure. I'd like to know whether this is a problem specific to `jedi-language-server`, or specific to Neovim's built-in language client's handling of file modification from plugins like Ale.

That said, I know that Ale is trying to be a LSP client as well, so maybe this behavior could be explained by some weird interplay between Ale and the built-in lsp.

Also, I just remembered that Ale has built-in jedi-language-server support. Maybe there's something weird going on because of that? <https://github.com/dense-analysis/ale/blob/01800a23addb52788265e0349f519556dab41301/ale_linters/python/jedils.vim>

**Comment by pappasam** [comment] 2021-05-21 00:19
@WhyNotHugo have you managed to resolve this issue yet? Wondering whether I should leave this ticket open based on our discussion that it may be an issue with other tooling

**Comment by WhyNotHugo** [comment] 2021-05-21 13:33
I think it's a multi-part issue:

- `neovim` should not be sending extra `didChange` messages.
- `jedi` should likely not emit errors like this -- they don't seem to be correct.
- `jedi` should maybe also finish reading all events before actually reacting and sending errors (e.g.: if more `didChange` events are pending, don't send errors yet, since they may be bogus).

I don't think it's ALE, since using `black` on the file directly (rather than via ALE) results in the same quirks.

That said, I haven't seen the issue lately. Something has changed somewhere and it's gone :man_shrugging:

**Comment by pappasam** [comment] 2021-09-30 20:49
Closing since this seems to disappeared for the OP and no one else has participated

**Closed by pappasam** 2021-09-30 20:49 UTC
