### ISSUE TITLE
Completions do not work for numpy

### ISSUE THREAD

**Issue by HansPinckaers** [pappasam/jedi-language-server#27] opened 2020-05-27 09:41 UTC
Hi there! Thanks for your work, jedi refactoring is so much better than rope. However, numpy completions is not working for me (does work with coc-python and vim-jedi), any idea how to debug?

Cheers,
Hans

**Comment by pappasam** [comment] 2020-05-27 13:45
Hi Hans, glad you're enjoying the refactorings, and hopefully we can resolve your numpy completions!

Unfortunately (or fortunately?), I cannot reproduce; numpy completes well for me. Questions:

1. Which version of `jedi-language-server` are you using? `jedi-language-server --version`
2. Which version of Vim/Neovim are you using? `vim/nvim --version`
3. Which OS are you using?
4. How is numpy installed for you? With `pip`, in a virtualenv, something else?
5. How are you using `jedi-language-server`? If Vim/Neovim with coc, I recommend https://github.com/pappasam/coc-jedi
6. Any other helpful information you can give me about your setup?

**Comment by HansPinckaers** [comment] 2020-05-27 17:58
It seems to not be able to autocomplete any installed packages. So I think something goes wrong with a path somewhere.

1:
```
❯ /home/hans/.config/coc/extensions/node_modules/coc-jedi/.venv/bin/jedi-language-server --version
jedi-language-server, version 0.15.1
```
```
❯ nvim --version
NVIM v0.5.0-519-g74fed7d50
```

3: OS: ubuntu 18.04

4: It's installed with (mini)conda in the default environment.

5: I'm using coc-jedi :-)

6: I have this property in my :CocConfig:   "python.pythonPath": "/home/hans/miniconda3/bin/python" although coc-python does also with without that property. Is it possible coc-jedi does not use the right python or doesn't find the packages?

**Comment by HansPinckaers** [comment] 2020-05-28 07:15
I installed the jedi-language-server myself with pip and added:
```
  "jedi.executable.command": "/home/hans/miniconda3/bin/jedi-language-server",
```

Now it works!

**Comment by pappasam** [comment] 2020-05-28 14:13
In that case, this issue relates to `coc-jedi` and not `jedi-language-server`. I'm closing this issue, but I've linked the `coc-jedi` issue above.

**Closed by pappasam** 2020-05-28 14:13 UTC
