### ISSUE TITLE
Markdown in docs looks like it highlights python keywords

### ISSUE THREAD

**Issue by karthiknadig** [pappasam/jedi-language-server#98] opened 2021-03-19 22:48 UTC
![image](https://user-images.githubusercontent.com/3840081/111849316-84efa000-88ca-11eb-9c9e-575fee3e670b.png)

**Comment by pappasam** [comment] 2021-03-20 17:01
Strange... which version of jedi-language-server is this being generated by? On version `0.28.4`, if your editor prefers markdown and you haven't explicitly configured your preferred markup as plaintext, jedi-language-server returns the following text wrapped in triple ticks without any language format specified:

![image](https://user-images.githubusercontent.com/3723671/111877943-f418d300-8962-11eb-9392-eb099b2b8ff5.png)

See: https://github.com/pappasam/jedi-language-server/pull/72/files

**Comment by karthiknadig** [comment] 2021-03-24 00:26
I will investigate this and move it accordingly. It might take me a couple of days to get to this.

**Comment by karthiknadig** [comment] 2021-03-26 08:41
![image](https://user-images.githubusercontent.com/3840081/112604212-2008de00-8dd3-11eb-8430-b860f5d10f1f.png)

This is the request and response for hover:
```
[Trace - 1:28:34 AM] Sending request 'textDocument/hover - (716)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/GIT/jedi-language-server/tests/test_data/hover/hover_test1.py"
    },
    "position": {
        "line": 2,
        "character": 14
    }
}


[Trace - 1:28:34 AM] Received response 'textDocument/hover - (716)' in 8ms.
Result: {
    "contents": {
        "kind": "markdown",
        "value": "```\nModule doc string for testing\n```\n"
    },
    "range": {
        "start": {
            "line": 2,
            "character": 7
        },
        "end": {
            "line": 2,
            "character": 17
        }
    }
}

```
I don't think the text should be wrapper in triple-back ticks.


This is form `pylance`, where we wrap only the name of the module in triple-back ticks:
![image](https://user-images.githubusercontent.com/3840081/112605171-3f543b00-8dd4-11eb-97d0-ad054082122d.png)

```
[Trace - 1:35:06 AM] Received response 'textDocument/hover - (16)' in 3ms.
Result: {
    "contents": {
        "kind": "markdown",
        "value": "```python\n(module) somemodule\n```\n---\nModule doc string for testing"
    },
    "range": {
        "start": {
            "line": 2,
            "character": 8
        },
        "end": {
            "line": 2,
            "character": 18
        }
    }
}
```

**Comment by krassowski** [comment] 2021-03-26 09:47
This is intended to show pre-formatted text from docstrings as such (preserving white spaces and using constant character width). 
IMO the issue is with you editor as fenced backticks without info string (language specifier) should not use syntax highlighting, see [common markdown specification and test cases](https://spec.commonmark.org/0.29/#fenced-code-blocks). In particular Python docstrings include code blocks of other languages which may not have universally supported code highlighters (e.g. production lists) or which cannot be determined from static analysis.

**Comment by krassowski** [comment] 2021-03-26 09:50
But if there are no indents at all AND we can safely assume there it is no code either then the backticks could be removed indeed.

**Comment by wyuenho** [comment] 2021-04-04 09:28
@karthiknadig Is this Emacs? Cause I'm seeing the same trace from lsp-mode's log. There are two issues here I believe, one is even if the server was initialized with `"markupKindPreferred": "plaintext"`, the completion documentation format returned from the server is still "markdown". Also, Emacs's lsp-mode is also doing something weird when rendering the completion documentation as well, as I think the docs are getting font-locked twice.

**Comment by wyuenho** [comment] 2021-04-04 10:46
There's also an additional problem: if the client declares capabilities `"completion.completionItem.documentationFormat": ["markdown", "plaintext"]`, and the server is set up to `"jedi.markupKindPreferred": "plaintext"`, the client capabilities still wins so there's not really a way to prefer plaintext in user configuation.

**Comment by wyuenho** [comment] 2021-04-04 11:58
Okay, my debugging session has nailed down to [this line](https://github.com/pappasam/jedi-language-server/blob/15d096c9bd5a745669618fe769b2b35ae8f380f8/jedi_language_server/server.py#L83), pretty sure init options isn't setting `markup_kind_preferred` here. I'm pretty sure I've sent the correct init params:

```json
  "initializationOptions": {
    "jedi": {
      "workspace": {
        "symbols": {
          "ignoreFolders": [
            ".nox",
            ".tox",
            ".venv",
            "__pycache__",
            "venv"
          ],
          "maxSymbols": 20
        }
      },
      "diagnostics": {
        "didSave": false,
        "didChange": false,
        "didOpen": false,
        "enable": false
      },
      "completion": {
        "resolveEagerly": false,
        "disableSnippets": false
      },
      "codeAction": {
        "nameExtractVariable": "jls_extract_var",
        "nameExtractFunction": "jls_extract_def"
      },
      "executable": {
        "args": [],
        "command": "jedi-language-server"
      },
      "jediSettings": {
        "caseInsensitiveCompletion": true,
        "autoImportModules": []
      },
      "trace": {
        "server": "messages"
      },
      "markupKindPreferred": "plaintext",
      "enable": true
    }
  }
```

**Comment by wyuenho** [comment] 2021-04-04 15:57
Ok this is my fault, lsp-jedi's initializationOptions shouldn't be nested inside an extra jedi dict...

**Comment by karthiknadig** [comment] 2021-04-04 17:26
@wyuenho This is from VS Code.

**Comment by pappasam** [comment] 2021-06-17 22:37
@karthiknadig I believe this has been resolved in the latest release. Please let me know if you think otherwise.

**Comment by karthiknadig** [comment] 2021-06-17 23:37
I will test this sometime this week. 

But we can't take this in the extension. Since we have not yet deprecated 3.6.*. If i understand correctly this now requires python greater than 3.6.2?

**Comment by pappasam** [comment] 2021-06-17 23:47
Ah, in that case I'll look into re-adding support for 3.6.0+.  Removing support simplified some thing for development dependencies, but since I don't think any regular dependencies are impacted, I can probably find a workaround. Stay tuned!

**Comment by pappasam** [comment] 2021-06-25 12:59
@karthiknadig jls 0.33.0 now supports all Python 3.6+!

**Comment by karthiknadig** [comment] 2021-06-25 13:52
@pappasam Thank you. I verified that this is fixed.

**Closed** 2021-06-25 17:37 UTC
